### ISSUE TITLE
Calling /uno after playing wild crashes bot

### ISSUE THREAD

**Issue by kingofzeal** [SignetStudios/slackbot-uno#31]
> [2017-04-18T17:05:31Z]slapp:info [evt] tm=T0AP3U2MA ch=C4Y9ES4VB usr=undefined message.message_changed
> [2017-04-18T17:05:39Z]slapp:info [cmd] tm=T0AP3U2MA ch=C4Y9ES4VB usr=U0HE6BYPR /uno
> [2017-04-18T17:05:39Z]/usr/src/app/slack_bot.js:54
> [2017-04-18T17:05:39Z] unoGame.setWildColor(msg, state, msg.body.actions[0].value);
> [2017-04-18T17:05:39Z] ^
> [2017-04-18T17:05:39Z]
> [2017-04-18T17:05:39Z]TypeError: Cannot read property '0' of undefined
> [2017-04-18T17:05:39Z] at slapp.route (/usr/src/app/slack_bot.js:54:54)
> [2017-04-18T17:05:39Z] at self.convoStore.del (/usr/src/app/node_modules/slapp/src/slapp.js:231:24)
> [2017-04-18T17:05:39Z] at /usr/src/app/node_modules/slapp-convo-beepboop/node_modules/beepboop-persist/index.js:82:9
> [2017-04-18T17:05:39Z] at wrapped (/usr/src/app/node_modules/hoek/lib/index.js:871:20)
> [2017-04-18T17:05:39Z] at Object.onceWrapper (events.js:293:19)
> [2017-04-18T17:05:39Z] at emitOne (events.js:96:13)
> [2017-04-18T17:05:39Z] at ClientRequest.emit (events.js:191:7)
> [2017-04-18T17:05:39Z] at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:522:21)
> [2017-04-18T17:05:39Z] at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
> [2017-04-18T17:05:39Z] at Socket.socketOnData (_http_client.js:411:20)
> [2017-04-18T17:05:39Z] at emitOne (events.js:96:13)
> [2017-04-18T17:05:39Z] at Socket.emit (events.js:191:7)
> [2017-04-18T17:05:39Z] at readableAddChunk (_stream_readable.js:178:18)
> [2017-04-18T17:05:39Z] at TCP.onread (net.js:559:20)

When playing a wild, should show the user their hand prior to the buttons, to reduce the need for calling /uno.

**Comment by bmuenzenmeyer** [comment]
oopsies! 👀
