### ISSUE TITLE
cannot win game on a wild

### ISSUE THREAD

**Issue by bmuenzenmeyer** [SignetStudios/slackbot-uno#38]
@kingofzeal said this might be a duplicate

**Comment by kingofzeal** [comment]
Looks like it's because the normal game checks don't occur when the color choice is processed, because it's expecting the normal play processing to handle them all. However, this clearly isn't the case with end-of-turn or end-of-game type checks.

Related to #37

**Comment by bmuenzenmeyer** [comment]
per @kingofzeal win condition could be added around https://github.com/SignetStudios/slackbot-uno/blob/master/lib/uno.js#L694
